.github/workflows/ci.yml
Follow-up for #3 to run the generator script in the CI to ensure that `types.py` and `types.dart` stay in sync.
NOTE: It's fine to merge a subiquity update that leaves the two out of sync. The bot will automatically open a PR with newly generated Dart files.
=> CI: generate subiquity types

pubspec.yaml
Reverts canonical/subiquity_client.dart#16 because it conflicts with gsettings.dart.
```
Because every version of subiquity_client from path depends on xdg_directories ^1.0.0 and gsettings >=0.2.0 depends on xdg_directories ^0.2.0, subiquity_client from path is incompatible with gsettings >=0.2.0.
So, because ubuntu_desktop_installer depends on both gsettings ^0.2.5 and subiquity_client from path, version solving failed.
```
=> Revert "Update dependency xdg_directories to v1"

.github/workflows/ci.yml
For the same reason as:
- https://github.com/canonical/ubuntu-desktop-installer/pull/1407
- https://github.com/canonical/ubuntu-desktop-installer/pull/1414
https://github.com/canonical/subiquity_client.dart/actions/runs/4194412472/jobs/7272542925
=> CI: use `make install_deps` for subiquity dependencies

lib/src/client.dart, test/subiquity_client_test.dart
No longer used: canonical/ubuntu-desktop-installer#1433
Services and models couldn't rely on isOpen because Subiquity is not immediately ready for use after opening the socket but needs some initialization first.
=> Remove SubiquityClient.isOpen

lib/src/client.dart, pubspec.yaml
Split off from #25.
`jsonEncode()` takes care of adding quotes around strings, and `jsonDecode()` returns strings without extra quotes and booleans as booleans. This is essentially the same as what Subiquity does in Python i.e. serializing and de-serializing to/from JSON. As a bonus, we get rid of the silly `dartx` dependency for... removing quotes, tada! (:
=> Use JsonCodec for query params and responses

lib/src/client.dart
Split off from #25.
Instead of awaiting request.close() in every single method and then passing the response to _receive(), just pass the response and await once in _receive().
=> Move repetitive request.close() calls into _receive()

lib/src/client.dart
Split off from #25.
Most method arguments were logged as is, whereas some were quoted, and some even converted to JSON. Just dump them all without any extra formatting because the involved primitive Dart types and the Freezed data classes have all nice built-in string formatting.
=> Clean up and simplify logging

lib/src/client.dart, test/subiquity_client_test.dart
There's still [more AD-related API coming](https://github.com/canonical/subiquity/pull/1572) but this PR implements API that has been added to Subiquity so far to get us going with the GUI-side work:
```python
class active_directory:
def GET() -> Optional[ADConnectionInfo]: ...
def POST(data: Payload[ADConnectionInfo]) -> None: ...
class has_support:
""" Whether the live system supports Active Directory or not.
Network status is not considered.
Clients should call this before showing the AD page. """
def GET() -> bool: ...
class check_domain_name:
def POST(domain_name: Payload[str]) \
-> List[AdDomainNameValidation]: ...
class check_admin_name:
def POST(admin_name: Payload[str]) -> AdAdminNameValidation: ...
class check_password:
def POST(password: Payload[str]) -> AdPasswordValidation: …
```
=> Initial Active Directory support

lib/src/client.dart, test/subiquity_client_test.dart
Subiquity runs as root. It doesn't know the desktop live session user. The GUI must pass the appropriate username to make it possible for Subiquity to change the desktop input source for the live session user. It defaults to 'ubuntu' which won't work for flavors that may have a different live session username.
The respective Subiquity API was added in https://github.com/canonical/subiquity/pull/1388 but the user-argument was forgotten from the Dart API. :man_shrugging: 
Ref: https://github.com/canonical/ubuntu-flavor-installer/issues/10
=> setInputSource(): add missing user-argument

test/subiquity_client_test.dart
Required for #47 to pass tests. Amazing that the storage v2 tests even passed previously...
=> Tests: add missing --storage-version=2

pubspec.yaml
dart_style 2.3.0 has formatting changes that cause differences between `dart format` and `dart pub run build_runner`. Pin version 2.2.x until the latest stable Dart SDK uses dart_style 2.3.0+.
- https://github.com/canonical/subiquity_client.dart/pull/52
- https://github.com/canonical/subiquity_client.dart/actions/runs/4411466308/jobs/7729993034
<details><summary>diff</summary>
```diff
diff --git a/test/status_monitor_test.mocks.dart b/test/status_monitor_test.mocks.dart
index f500667..dd41dff 100644
--- a/test/status_monitor_test.mocks.dart
+++ b/test/status_monitor_test.mocks.dart
@@ -167,11 +167,10 @@ class MockHttpClient extends _i1.Mock implements _i2.HttpClient {
@override
set authenticate(
_i4.Future<bool> Function(
-    Uri,
-    String,
-    String?,
-  )?
-              f) =>
+ …
```
=> Pin dart_style version

lib/src/client.dart, test/subiquity_client_test.dart
This can be used to check whether Subiquity thinks we're online.
=> Add SubiquityClient.hasNetwork()

lib/src/client.dart, test/subiquity_client_test.dart
Half of the GET requests had a get-prefix while the others (earliest added ones) didn't. It's not only nice to have consistent but it also emphasizes the behavior of the API. At the same time, this paves the road for merging SubiquityStatusMonitor into SubiquityClient by freeing up the "status" name for a synchronous getter for accessing the latest known status. The end goal is to make it easier to access and present the status anywhere in the GUI.
=> Consistent naming of GET requests

lib/src/extensions.dart, test/types_test.dart
The sysname extensions are used everywhere in UDI because of being used as display names for disks and partitions. Currently, they are exported from the "disk storage service" which is being trimmed down and probably split into smaller entities. Exporting them from here makes them flow down everywhere SubiquityClient is used and where the storage service is not necessarily needed.
=> Import common Disk & Partition extensions from UDI

pubspec.yaml, test/status_monitor_test.mocks.dart
Reverts canonical/subiquity_client.dart#53 because Dart 3 was released
> TODO: dart_style 2.3.0 has some formatting changes that cause differences
> between `dart format` and `dart pub run build_runner`. Remove this when the
> latest stable Dart SDK uses dart_style 2.3.0+.
=> Revert "Pin dart_style version"

lib/src/client.dart, packages/subiquity_test/lib/src/generated.mocks.dart
With this, the client's status changes can be conveniently listened to through the same client instance without injecting a separate status monitor service or passing both the client and a monitor around.
=> feat: add `SubiquityClient.monitorStatus()` for convenience

pubspec.yaml
A workaround for:
```
[SEVERE] json_serializable on lib/src/types.dart:
Could not generate `fromJson` code for `gap`.
To support the type `InvalidType` you can:
* Use `JsonConverter`
https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html
* Use `JsonKey` fields `fromJson` and `toJson`
https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/fromJson.html
https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/toJson.html
package:subiquity_client/src/types.freezed.dart:6788:21
╷
6788 │   final InvalidType gap;
│                     ^^^
╵
```
Close: #119
=> chore: pin analyzer version

lib/src/client.dart, packages/subiquity_test/lib/src/generated.mocks.dart, test/subiquity_client_test.dart
This simplifies querying the locale on startup. We don't know when the endpoint has been resolved, the server is up and running, and the client has been opened. Instead of throwing null-assertion errors when a wrong method is called too soon based on conditions that are not even known from the outside, just return a future that completes when the conditions are met and the query can be processed.
=> fix: null assertion when getXxx() is called before open()

lib/src/status_monitor.dart, test/status_monitor_test.dart
The status turns into null if Subiquity sends an error response due to an exception being thrown on the server side. We should do the same if an exception (HTTP, socket, ...) is thrown on the client side.
=> fix: catch exceptions when monitoring status

pubspec.yaml
```
[INFO] Generating build script completed, took 161ms
[INFO] Reading cached asset graph completed, took 35ms
[INFO] Checking for updates since last build completed, took 353ms
[WARNING] json_serializable on lib/src/types.dart:
The version constraint "^4.8.0" on json_annotation allows versions before 4.8.1 which is not allowed.
[INFO] Running build completed, took 4.2s
[INFO] Caching finalized dependency graph completed, took 24ms
[INFO] Succeeded after 4.3s with 4 outputs (4 actions)
```
```
[INFO] Generating build script completed, took 174ms
[INFO] Reading cached asset graph completed, took 38ms
[INFO] Checking for updates since last build completed, took 324ms
[INFO] Running build completed, took 4.2s
[INFO] Caching finalized dependency graph completed, took 15ms
[INFO] Succeeded …
```
=> chore(deps): bump json_annotation to make build_runner happy

lib/src/client.dart
Properly handle the case where AD domain name is empty and return an empty json instead of a null value.
Closes: lp:#2033881
=> Do not crash if AD domain name is empty

.gitmodules
Updates the current submodule reference to `ubuntu/mantic` and makes sure that dependabot uses the same reference.
=> feat: track subiquity's ubuntu/mantic branch
